name: test

on:
  push:
    branches: master

jobs:
  build-latest-tag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run test
        run: make all
