name: test

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup docker
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Makefile
        run: make all
